Gestion_Almacenes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from almacen import urls as almacen
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('almacen.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

almacen/urls.py
from django.urls import include, path
from rest_framework import routers
from .views import DashboardView,ModalProductView,AddCanvasShoppingCart,DropShoppingCart,CartView,\
    DeleteCartView,CheckoutView,CreateTransactionView,SuccessfulView,ErrorView,DeliveryView,\
    InventarioAlert,IndexAdminView,TransacitonAdminView,DetailVentasView,AdminProductView,\
    AdminGraphicsView,GraphProductView,GraphicsStatistView,TransacitonAdminViewad,custom_login
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'almacen'



urlpatterns = [

    path('', DashboardView.as_view(), name='dashboard'),
    path('admingraph/', IndexAdminView.as_view(), name='index_admin'),
    path('ventas/', TransacitonAdminView.as_view(), name='ventas'),
    path('ventasadmin/', TransacitonAdminViewad.as_view(), name='ventasadmin'),

    path('detailventas/',DetailVentasView.as_view(),name="detailventas"),#retornamos a la template de transactionsadmin el detalle de la transaccion seleccionada

    path('get-admin-product-modal/', AdminProductView.as_view(), name="get_admin_product"),   #modal del producto en el admin
    path('admins-tatistics/', AdminGraphicsView.as_view(), name="get_admin_graphics"),#template con las estadisticas de las ventas
    path('graphadmin/',GraphProductView.as_view(),name="graphproduct"),#graficadora del modal
    path('graphicsstatistics/',GraphicsStatistView.as_view(),name="graphics_statistics"),#graficadora del template de estadisticas

    path('alert/', InventarioAlert.as_view(), name='alert'),
    path('login/', custom_login, name='login'),
	path('logout/',LogoutView.as_view(), name='logout'),
    path('get-product-modal/', ModalProductView.as_view(), name='get_product_modal'),
    path('add-shopping-cart/',AddCanvasShoppingCart.as_view(), name='add-shopping-cart'),
    path('drop-shopping-cart/',DropShoppingCart.as_view(), name='drop-shopping-cart'),
    path('view-cart/', CartView.as_view() ,name='view-cart'),
    path('delete-cart/', DeleteCartView.as_view() ,name='delete-cart'),
    path('checkout/', CheckoutView.as_view() ,name='checkout'),
    path('transaction/', CreateTransactionView.as_view() ,name='transaction'),
    path('successful/', SuccessfulView.as_view() ,name='successful'),
    path('error/', ErrorView.as_view() ,name='errorview'),
    path('delivery/', DeliveryView.as_view(),name="delivery"),

]

almacen/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,View,TemplateView
from django.shortcuts import get_object_or_404
from .models import ProductInformation,ProductImage,Category,GeneralSetting,Venta
from almacen.utils import articulosComprados,dictionari_shopping,cant_product_transaction,information_transaction,dias_amount,\
amount_id,dias_compras
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.core.paginator import Paginator
from .form import TransactionForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import UserPassesTestMixin
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import base64
import io
from django.contrib.auth import login
from django.urls import reverse_lazy
from django.contrib.auth.forms import AuthenticationForm

def custom_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if user.is_superuser:
                return redirect('admin:index')
            else:
                return redirect('almacen:dashboard')
    else:
        form = AuthenticationForm(request)

    context = {
        'form': form,
    }
    return render(request, 'core/login.html', context)

@method_decorator(login_required, name='dispatch')
class DashboardView(ListView):

    template_name = 'core/dashboard_base.html'
    model = ProductInformation
    queryset = ProductInformation.objects.all().order_by('-id')
    paginate_by = 6 # Define la cantidad de elementos por página
    
    def get_queryset(self):
        search = self.request.GET.get('search')
        category = self.request.GET.get('category')

        
        if search:
            name = self.queryset.filter(name_product__icontains=search).order_by('-id')
            idproduct = self.queryset.filter(reference_product__icontains=search).order_by('-id')
            if name:
                self.queryset=name
            else:
                self.queryset=idproduct


        if category:
            self.queryset = self.queryset.filter(categories__name=category).order_by('-id')
        # El ordenamiento se realiza antes de la paginación
        return self.queryset

    def get_context_data(self, **kwargs):
        if(self.request.user.is_superuser):
            redirect('/admin')
        context = super().get_context_data(**kwargs)
        self.category_list = Category.objects.all()
        context['category_list'] = self.category_list
        # Agrega el paginador al contexto
        paginator = Paginator(self.queryset, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj
        return context

@method_decorator(login_required, name='dispatch')
class DeleteCartView(View):
    template_name='core/components/canvas/shopping_cart.html'
    def get(self,request,*args, **kwargs):
        # Obtener el id del producto que se agrega al carrito
        delete_product_id= request.GET.get('delete_product_id')

        # se obitiene el producto el cual se agrego al carrito
        product= ProductInformation.objects.get(pk=delete_product_id)

        # Obtener el carrito de compras actual del usuario
        cart = request.session.get('cart', {})
        # Agregar el producto al carrito o actualizar la cantidad si ya está en el carrito
        if delete_product_id in cart:
           
            product.quantity+=cart[delete_product_id]['quantity']
            product.save()
            cart.pop(delete_product_id, None)
            request.session['cart'] = cart

        cartS= request.GET.get('cart')
        if cartS=='cart':
            return redirect('almacen:body_cart')
        else:
            return redirect('almacen:view-cart')

@method_decorator(login_required, name='dispatch')
class AddCanvasShoppingCart(View):
    template_name = 'core/components/canvas/shopping_cart.html'
    def get(self,request,*args, **kwargs):
        # Obtener el id del producto que se agrega al carrito
        product_id= request.GET.get('product_id')

        

        # Obtener la cantidad de productos
        #quantity= request.GET.get('quantity')

        # se obitiene el producto el cual se agrego al carrito
        product= ProductInformation.objects.get(pk=product_id)

        # Obtener el carrito de compras actual del usuario
        cart = request.session.get('cart', {})
        # Agregar el producto al carrito o actualizar la cantidad si ya está en el carrito
        if product_id in cart:
            cart[product_id]['quantity'] += 1
            product.quantity-=1
            product.save()
            
        else:
            cart[product_id] = {
                'name': product.name_product,
                'image': product.images.all()[0].image.url,
                'price': float(product.price_product),
                'quantity': 1
            }
            product.quantity-=1
            product.save()
        request.session['cart'] = cart
        cartS= request.GET.get('cart')
        if cartS=='cart':
            return redirect('almacen:body_cart')
        else:
            return redirect('almacen:view-cart')

@method_decorator(login_required, name='dispatch')        
class DropShoppingCart(View):
    template_name = 'core/components/canvas/shopping_cart.html'
    def get(self,request,*args, **kwargs):
        # Obtener el id del producto que se agrega al carrito
        product_id= request.GET.get('drop_product_id')

        # Obtener la cantidad de productos
        #quantity= request.GET.get('quantity')

        # se obitiene el producto el cual se agrego al carrito
        product= ProductInformation.objects.get(pk=product_id)
        cartS= request.GET.get('cart')
        # Obtener el carrito de compras actual del usuario
        cart = request.session.get('cart', {})
        # Agregar el producto al carrito o actualizar la cantidad si ya está en el carrito
        if product_id in cart:
            if cart[product_id]['quantity'] > 0:
                cart[product_id]['quantity'] -= 1
                product.quantity+=1
                product.save()
            else:
                if cartS=='cart':
                    url = reverse('almacen:delete-cart') + '?delete_product_id=' + str(product_id + '&cart=cart')
                    return HttpResponseRedirect(url)
                else:
                    url = reverse('almacen:delete-cart') + '?delete_product_id=' + str(product_id)
                    return HttpResponseRedirect(url)
                

        request.session['cart'] = cart


        
        if cartS=='cart':
            return redirect('almacen:body_cart')
        else:
            return redirect('almacen:view-cart')

#el carrito que es modal pequeño
@method_decorator(login_required, name='dispatch')
class CartView(View):
    template_name = 'core/components/canvas/shopping_cart.html'

    def get(self, request):
        # Obtener el carrito de compras actual del usuario
        cart = request.session.get('cart', {})
        
        # Calcular el precio total del carrito de compras
        total_price = sum(item['price'] * item['quantity'] for item in cart.values())

        sub_total_price = {}
        for product_id, item in cart.items():
            sub_total_price[product_id] = item['price'] * item['quantity']

        # Renderizar la plantilla con el carrito actual y el precio total
        return render(request, self.template_name , {'cart': cart, 'total_price': total_price,'sub_total_price':sub_total_price})


@method_decorator(login_required, name='dispatch')
class ModalProductView(View):


    template_name = 'core/components/modals/modal_product.html'

    def get(self, request, *args, **kwargs):
        product_id= request.GET.get('product_id')
        product= ProductInformation.objects.get(pk=product_id)
        return render(request, self.template_name, {'product':product})
   
@method_decorator(login_required, name='dispatch')
class CheckoutView(View):
    template_name = 'core/checkout.html'
    def get(self, request, *args, **kwargs):
        # Obtener el carrito de compras actual del usuario
        cart = request.session.get('cart', {})
        typedelivery=request.GET.get('typedelivery')
        # Calcular el precio total del carrito de compras
        price = sum(item['price'] * item['quantity'] for item in cart.values())
        
      

        
        context={
            'cart': cart,
            'price': price,
        }
        
        # Renderizar la plantilla con el carrito actual y el precio total
        return render(request, self.template_name, context)

@method_decorator(login_required, name='dispatch')
class CreateTransactionView(View):
    


    def post(self,request):
        
        instance=TransactionForm(request.POST)
        if instance.is_valid():
            transaction=instance.save(commit=False)
            articles=articulosComprados(request)
            transaction.articles=articles
            transaction.save()

            cart = request.session.get('cart', {})
            del request.session['cart']


            return redirect('almacen:successful')
            
        else:
            print(instance.errors)
            print(instance)
            return JsonResponse({'error':'error'})
            
@method_decorator(login_required, name='dispatch')        
class SuccessfulView(TemplateView):
    template_name= 'core/successful.html'


class ErrorView(TemplateView):
    template_name= 'core/error.html'
@method_decorator(login_required, name='dispatch')
class InventarioAlert(TemplateView):
    template_name= 'core/components/modals/dialog.html'
    

class DeliveryView(View):

almacen/templates/core/components/footer.html
{% load static i18n %}

      <!-- footer start -->
        <footer class="mt-100 overflow-hidden">
            <div class=" bg-4">
                <div class="container">
                    <div class="footer-widget-wrapper">
                        <div class="row justify-content-between">
                            <div class="col-xl-2 col-lg-2 col-md-6 col-12 footer-widget">
                                <div class="footer-widget-inner">
                                    <h4 class="footer-heading d-flex align-items-center justify-content-between" style="margin: 50% 0 50% 0 ;">
                                        <span>{% trans 'Sobre Nosotros' %}</span>
                                        <span class="d-md-none">
                                            <svg class="icon icon-dropdown" xmlns="http://www.w3.org/2000/svg"
                                                width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#fff"
                                                stroke-width="1" stroke-linecap="round" stroke-linejoin="round">
                                                <polyline points="6 9 12 15 18 9"></polyline>
                                            </svg>
                                        </span>
                                    </h4>
                                  
                                </div>
                            </div>
                            <div class="col-xl-2 col-lg-2 col-md-6 col-12 footer-widget">
                                <div class="footer-widget-inner">
                                    <h4 class="footer-heading d-flex align-items-center justify-content-between" style="margin: 50% 0 50% 0 ;" >
                                        <span>{% trans 'Compras' %}</span>
                                        <span class="d-md-none">
                                            <svg class="icon icon-dropdown" xmlns="http://www.w3.org/2000/svg"
                                                width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#fff"
                                                stroke-width="1" stroke-linecap="round" stroke-linejoin="round">
                                                <polyline points="6 9 12 15 18 9"></polyline>
                                            </svg>
                                        </span>
                                    </h4>
                                 
                                </div>
                            </div>
                            <div class="col-xl-2 col-lg-2 col-md-6 col-12 footer-widget">
                                <div class="footer-widget-inner">
                                    <h4 class="footer-heading d-flex align-items-center justify-content-between" style="margin: 50% 0 50% 0 ;">
                                        <span>{% trans 'Soporte' %}</span>
                                        <span class="d-md-none">
                                            <svg class="icon icon-dropdown" xmlns="http://www.w3.org/2000/svg"
                                                width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#fff"
                                                stroke-width="1" stroke-linecap="round" stroke-linejoin="round">
                                                <polyline points="6 9 12 15 18 9"></polyline>
                                            </svg>
                                        </span>
                                    </h4>
                             
                                </div>
                            </div>
                            <div class="col-xl-4 col-lg-5 col-md-6 col-12 footer-widget">
                                <div class="footer-widget-inner">
                                    <h4 class="footer-logo d-flex justify-content-center align-items-center" style="margin: 8px 0 1px 0;">
                                        <a href="#"><img src="{{ settings.logo.url }}" alt="GainUp." height="60"></a>
                                    </h4>
                                    <div class="footer-newsletter">
                                        <p class="footer-text mb-3 d-flex justify-content-center align-items-center">{% trans 'Este al pendiente de todo las novedades!' %}</p>
                                        <div class="newsletter-wrapper">
                                            <form action="#" class="footer-newsletter-form d-flex align-items-center" style="margin: 10px 0 10px 0 ;">
                                                <input class="footer-newsletter-input bg-transparent" type="email"
                                                    placeholder="Your e-mail" autocomplete="off">
                                                <button class="footer-newsletter-btn newsletter-btn-white"
                                                    type="submit">{% trans 'Enviar' %}</button>
                                            </form>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-bottom bg-4">
                <div class="container">
                    <div
                        class="footer-bottom-inner d-flex flex-wrap justify-content-md-between justify-content-center align-items-center">
                        <ul class="footer-bottom-menu list-unstyled d-flex flex-wrap align-items-center mb-0">
                            <li class="footer-menu-item"><a href="#">{% trans 'Politicas de privacidad' %}</a></li>
                            <li class="footer-menu-item"><a href="#">{% trans 'Terminos y condiciones' %}</a></li>
                        </ul>
                        <p class="copyright footer-text">© <span class="current-year"></span>{% trans 'EasyStorage' %}</p>
                    </div>
                </div>
            </div>
        </footer>

almacen/templates/core/components/nav_bar.html
{% load static %} 
{% load static i18n %}
<header class="sticky-header border-btm-black header-1">
    <div class="header-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-3 col-md-3 col-4">
                    <div class="header-logo">
                        <a href="{% url 'almacen:dashboard' %}" class="logo-main">
                            
                            <img src="{{ settings.logo.url }}" loading="lazy" alt="GainUp" height="60">
                        </a>
                    </div>
                    
                </div>
                <div class="col-lg-1 col-md-6 col-4 text-center">
                    <nav class="site-navigation">
                        <div class="mega-menu-header linkventas">
                            <a class="nav-link d-block d-lg-none" href="{% url 'almacen:ventas' %}">
                                {% trans 'Ventas' %}
                            </a>
                        </div>
                    </nav>
                </div> 
<style>
    @media (max-width: 990px) {
    .linkventas {
      display: block;
    }
    
    .linkventas .nav-link {
      display: inline-block;
      color: var(--secondary-color);
    }
  }
  </style>                  
                <div class="col-lg-5 d-lg-block d-none">
                    <nav class="site-navigation">
                        <ul class="main-menu list-unstyled justify-content-center">
                            <li class="menu-list-item nav-item has-dropdown active">
                                <div class="mega-menu-header">
                                    <a id="homelink" class="nav-link" href="{% url 'almacen:dashboard' %}">
                                        {% trans 'Inicio' %} 
                                    </a>
                                    
                                </div>
                                
                            </li>
                            <div id="linknavbar">

                            </div>
                            <li class="menu-list-item nav-item has-dropdown active">
                                <div class="mega-menu-header">
                                    <a id="ventaslink" class="nav-link" href="{% url 'almacen:ventas' %}">
                                        {% trans 'Ventas' %} 
                                    </a>
                                    
                                </div>
                                
                            </li>
                            
                            
                            
                             
                        </ul>
                    </nav>
                </div>

                <div class="col-lg-3 col-md-3 col-3">
                    <div class="header-action d-flex align-items-center justify-content-end">
                        <a class="header-action-item header-search" href="javascript:void(0)">
                            <svg class="icon icon-search" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M7.75 0.250183C11.8838 0.250183 15.25 3.61639 15.25 7.75018C15.25 9.54608 14.6201 11.1926 13.5625 12.4846L19.5391 18.4611L18.4609 19.5392L12.4844 13.5627C11.1924 14.6203 9.5459 15.2502 7.75 15.2502C3.61621 15.2502 0.25 11.884 0.25 7.75018C0.25 3.61639 3.61621 0.250183 7.75 0.250183ZM7.75 1.75018C4.42773 1.75018 1.75 4.42792 1.75 7.75018C1.75 11.0724 4.42773 13.7502 7.75 13.7502C11.0723 13.7502 13.75 11.0724 13.75 7.75018C13.75 4.42792 11.0723 1.75018 7.75 1.75018Z" fill="black"></path>
                            </svg>
                        </a>
                        
                        <a  class="header-action-item header-cart ms-4" href="#drawer-cart" data-bs-toggle="offcanvas" onclick="open_cart()">
                            <svg class="icon  icon-cart"  width="24" height="26" viewBox="0 0 24 26" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M12 0.000183105C9.25391 0.000183105 7 2.25409 7 5.00018V6.00018H2.0625L2 6.93768L1 24.9377L0.9375 26.0002H23.0625L23 24.9377L22 6.93768L21.9375 6.00018H17V5.00018C17 2.25409 14.7461 0.000183105 12 0.000183105ZM12 2.00018C13.6562 2.00018 15 3.34393 15 5.00018V6.00018H9V5.00018C9 3.34393 10.3438 2.00018 12 2.00018ZM3.9375 8.00018H7V11.0002H9V8.00018H15V11.0002H17V8.00018H20.0625L20.9375 24.0002H3.0625L3.9375 8.00018Z" fill="black"></path>
                            </svg>
                        </a>
                        <a class="header-action-item header-search" href="{% url 'almacen:logout' %}" style="color:black; margin:8px 5px 5px 12px; font-size:28px;">
                            <span class="material-symbols-outlined">
                                logout
                                </span>
                        </a>

                            {% if user_data.image %}
                                <div class="text-center">
                                    
                                    <div class="d-flex align-items-center justify-content-center " data-bs-toggle="collapse" data-bs-target="#referredinformation"style="margin:0px 20px 0px 3px;">
                                    
                                        <div class="avatar-container">
                                            <img class="avatar-img" src="{{user_data.image}}" alt="">
                                        </div>
                                    </div>
                                    
                                </div>
                            {% endif %}
                              
                              
                              
                              
                              

                        
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="search-wrapper">
            <div class="container">
                <form action="{% url 'almacen:dashboard' %}"  class="search-form d-flex align-items-center" method="GET">
                    <button type="submit" class="search-submit bg-transparent pl-0 text-start">
                        <svg class="icon icon-search" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M7.75 0.250183C11.8838 0.250183 15.25 3.61639 15.25 7.75018C15.25 9.54608 14.6201 11.1926 13.5625 12.4846L19.5391 18.4611L18.4609 19.5392L12.4844 13.5627C11.1924 14.6203 9.5459 15.2502 7.75 15.2502C3.61621 15.2502 0.25 11.884 0.25 7.75018C0.25 3.61639 3.61621 0.250183 7.75 0.250183ZM7.75 1.75018C4.42773 1.75018 1.75 4.42792 1.75 7.75018C1.75 11.0724 4.42773 13.7502 7.75 13.7502C11.0723 13.7502 13.75 11.0724 13.75 7.75018C13.75 4.42792 11.0723 1.75018 7.75 1.75018Z" fill="black"></path>
                        </svg>
                    </button>
                    <div class="search-input mr-4">
                        <input type="text" placeholder="Search your products..." id="search-input"  autocomplete="off" name="search">
                    </div>
                    <div class="search-close">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-close">
                            <line x1="18" y1="6" x2="6" y2="18"></line>
                            <line x1="6" y1="6" x2="18" y2="18"></line>
                        </svg>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
</header>