Gestion_Almacenes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from almacen import urls as almacen
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('almacen.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

almacen/urls.py
from django.urls import include, path
from rest_framework import routers
from .views import DashboardView,ModalProductView,AddCanvasShoppingCart,DropShoppingCart,CartView,\
    DeleteCartView,CheckoutView,CreateTransactionView,SuccessfulView,ErrorView,DeliveryView,\
    InventarioAlert,IndexAdminView,TransacitonAdminView,DetailVentasView,AdminProductView,\
    AdminGraphicsView,GraphProductView,GraphicsStatistView,TransacitonAdminViewad,custom_login
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'almacen'



urlpatterns = [

    path('', DashboardView.as_view(), name='dashboard'),
    path('admingraph/', IndexAdminView.as_view(), name='index_admin'),
    path('ventas/', TransacitonAdminView.as_view(), name='ventas'),
    path('ventasadmin/', TransacitonAdminViewad.as_view(), name='ventasadmin'),

    path('detailventas/',DetailVentasView.as_view(),name="detailventas"),#retornamos a la template de transactionsadmin el detalle de la transaccion seleccionada

    path('get-admin-product-modal/', AdminProductView.as_view(), name="get_admin_product"),   #modal del producto en el admin
    path('admins-tatistics/', AdminGraphicsView.as_view(), name="get_admin_graphics"),#template con las estadisticas de las ventas
    path('graphadmin/',GraphProductView.as_view(),name="graphproduct"),#graficadora del modal
    path('graphicsstatistics/',GraphicsStatistView.as_view(),name="graphics_statistics"),#graficadora del template de estadisticas

    path('alert/', InventarioAlert.as_view(), name='alert'),
    path('login/', custom_login, name='login'),
	path('logout/',LogoutView.as_view(), name='logout'),
    path('get-product-modal/', ModalProductView.as_view(), name='get_product_modal'),
    path('add-shopping-cart/',AddCanvasShoppingCart.as_view(), name='add-shopping-cart'),
    path('drop-shopping-cart/',DropShoppingCart.as_view(), name='drop-shopping-cart'),
    path('view-cart/', CartView.as_view() ,name='view-cart'),
    path('delete-cart/', DeleteCartView.as_view() ,name='delete-cart'),
    path('checkout/', CheckoutView.as_view() ,name='checkout'),
    path('transaction/', CreateTransactionView.as_view() ,name='transaction'),
    path('successful/', SuccessfulView.as_view() ,name='successful'),
    path('error/', ErrorView.as_view() ,name='errorview'),
    path('delivery/', DeliveryView.as_view(),name="delivery"),

]

almacen/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,View,TemplateView
from django.shortcuts import get_object_or_404
from .models import ProductInformation,ProductImage,Category,GeneralSetting,Venta
from almacen.utils import articulosComprados,dictionari_shopping,cant_product_transaction,information_transaction,dias_amount,\
amount_id,dias_compras
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.core.paginator import Paginator
from .form import TransactionForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import UserPassesTestMixin
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import base64
import io
from django.contrib.auth import login
from django.urls import reverse_lazy
from django.contrib.auth.forms import AuthenticationForm

def custom_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if user.is_superuser:
                return redirect('admin:index')
            else:
                return redirect('almacen:dashboard')
    else:
        form = AuthenticationForm(request)

    context = {
        'form': form,
    }
    return render(request, 'core/login.html', context)

@method_decorator(login_required, name='dispatch')
class DashboardView(ListView):

    template_name = 'core/dashboard_base.html'
    model = ProductInformation
    queryset = ProductInformation.objects.all().order_by('-id')
    paginate_by = 6 # Define la cantidad de elementos por página
    
    def get_queryset(self):
        search = self.request.GET.get('search')
        category = self.request.GET.get('category')

        
        if search:
            name = self.queryset.filter(name_product__icontains=search).order_by('-id')
            idproduct = self.queryset.filter(reference_product__icontains=search).order_by('-id')
            if name:
                self.queryset=name
            else:
                self.queryset=idproduct


        if category:
            self.queryset = self.queryset.filter(categories__name=category).order_by('-id')
        # El ordenamiento se realiza antes de la paginación
        return self.queryset

    def get_context_data(self, **kwargs):
        if(self.request.user.is_superuser):
            redirect('/admin')
        context = super().get_context_data(**kwargs)
        self.category_list = Category.objects.all()
        context['category_list'] = self.category_list
        # Agrega el paginador al contexto
        paginator = Paginator(self.queryset, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj
        return context

@method_decorator(login_required, name='dispatch')
class DeleteCartView(View):
    template_name='core/components/canvas/shopping_cart.html'
    def get(self,request,*args, **kwargs):
        # Obtener el id del producto que se agrega al carrito
        delete_product_id= request.GET.get('delete_product_id')

        # se obitiene el producto el cual se agrego al carrito
        product= ProductInformation.objects.get(pk=delete_product_id)

        # Obtener el carrito de compras actual del usuario
        cart = request.session.get('cart', {})
        # Agregar el producto al carrito o actualizar la cantidad si ya está en el carrito
        if delete_product_id in cart:
           
            product.quantity+=cart[delete_product_id]['quantity']
            product.save()
            cart.pop(delete_product_id, None)
            request.session['cart'] = cart

        cartS= request.GET.get('cart')
        if cartS=='cart':
            return redirect('almacen:body_cart')
        else:
            return redirect('almacen:view-cart')

@method_decorator(login_required, name='dispatch')
class AddCanvasShoppingCart(View):
    template_name = 'core/components/canvas/shopping_cart.html'
    def get(self,request,*args, **kwargs):
        # Obtener el id del producto que se agrega al carrito
        product_id= request.GET.get('product_id')

        

        # Obtener la cantidad de productos
        #quantity= request.GET.get('quantity')

        # se obitiene el producto el cual se agrego al carrito
        product= ProductInformation.objects.get(pk=product_id)

        # Obtener el carrito de compras actual del usuario
        cart = request.session.get('cart', {})
        # Agregar el producto al carrito o actualizar la cantidad si ya está en el carrito
        if product_id in cart:
            cart[product_id]['quantity'] += 1
            product.quantity-=1
            product.save()
            
        else:
            cart[product_id] = {
                'name': product.name_product,
                'image': product.images.all()[0].image.url,
                'price': float(product.price_product),
                'quantity': 1
            }
            product.quantity-=1
            product.save()
        request.session['cart'] = cart
        cartS= request.GET.get('cart')
        if cartS=='cart':
            return redirect('almacen:body_cart')
        else:
            return redirect('almacen:view-cart')

@method_decorator(login_required, name='dispatch')        
class DropShoppingCart(View):
    template_name = 'core/components/canvas/shopping_cart.html'
    def get(self,request,*args, **kwargs):
        # Obtener el id del producto que se agrega al carrito
        product_id= request.GET.get('drop_product_id')

        # Obtener la cantidad de productos
        #quantity= request.GET.get('quantity')

        # se obitiene el producto el cual se agrego al carrito
        product= ProductInformation.objects.get(pk=product_id)
        cartS= request.GET.get('cart')
        # Obtener el carrito de compras actual del usuario
        cart = request.session.get('cart', {})
        # Agregar el producto al carrito o actualizar la cantidad si ya está en el carrito
        if product_id in cart:
            if cart[product_id]['quantity'] > 0:
                cart[product_id]['quantity'] -= 1
                product.quantity+=1
                product.save()
            else:
                if cartS=='cart':
                    url = reverse('almacen:delete-cart') + '?delete_product_id=' + str(product_id + '&cart=cart')
                    return HttpResponseRedirect(url)
                else:
                    url = reverse('almacen:delete-cart') + '?delete_product_id=' + str(product_id)
                    return HttpResponseRedirect(url)
                

        request.session['cart'] = cart


        
        if cartS=='cart':
            return redirect('almacen:body_cart')
        else:
            return redirect('almacen:view-cart')

#el carrito que es modal pequeño
@method_decorator(login_required, name='dispatch')
class CartView(View):
    template_name = 'core/components/canvas/shopping_cart.html'

    def get(self, request):
        # Obtener el carrito de compras actual del usuario
        cart = request.session.get('cart', {})
        
        # Calcular el precio total del carrito de compras
        total_price = sum(item['price'] * item['quantity'] for item in cart.values())

        sub_total_price = {}
        for product_id, item in cart.items():
            sub_total_price[product_id] = item['price'] * item['quantity']

        # Renderizar la plantilla con el carrito actual y el precio total
        return render(request, self.template_name , {'cart': cart, 'total_price': total_price,'sub_total_price':sub_total_price})


@method_decorator(login_required, name='dispatch')
class ModalProductView(View):


    template_name = 'core/components/modals/modal_product.html'

    def get(self, request, *args, **kwargs):
        product_id= request.GET.get('product_id')
        product= ProductInformation.objects.get(pk=product_id)
        return render(request, self.template_name, {'product':product})
   
@method_decorator(login_required, name='dispatch')
class CheckoutView(View):
    template_name = 'core/checkout.html'
    def get(self, request, *args, **kwargs):
        # Obtener el carrito de compras actual del usuario
        cart = request.session.get('cart', {})
        typedelivery=request.GET.get('typedelivery')
        # Calcular el precio total del carrito de compras
        price = sum(item['price'] * item['quantity'] for item in cart.values())
        
      

        
        context={
            'cart': cart,
            'price': price,
        }
        
        # Renderizar la plantilla con el carrito actual y el precio total
        return render(request, self.template_name, context)

@method_decorator(login_required, name='dispatch')
class CreateTransactionView(View):
    


    def post(self,request):
        
        instance=TransactionForm(request.POST)
        if instance.is_valid():
            transaction=instance.save(commit=False)
            articles=articulosComprados(request)
            transaction.articles=articles
            transaction.save()

            cart = request.session.get('cart', {})
            del request.session['cart']


            return redirect('almacen:successful')
            
        else:
            print(instance.errors)
            print(instance)
            return JsonResponse({'error':'error'})
            
@method_decorator(login_required, name='dispatch')        
class SuccessfulView(TemplateView):
    template_name= 'core/successful.html'


class ErrorView(TemplateView):
    template_name= 'core/error.html'
@method_decorator(login_required, name='dispatch')
class InventarioAlert(TemplateView):
    template_name= 'core/components/modals/dialog.html'
    

class DeliveryView(View):

almacen/templates/core/admin_transactions.html
{% extends 'core/base.html' %}
{% load static i18n %}
{% load discount_percentage %}
{% load int_custom_filters %}

{% block title %}
{% trans 'EasyStorage Admin' %}
{% endblock title%}

{% block extra_css %}
<style>
    h1 {
        font-size: 48px;
        font-weight: bold;
        color: var(--primary-color);
        text-align: center;
        text-transform: uppercase;
        letter-spacing: 2px;
        margin-top: 40px;
        margin-bottom: 20px;
        opacity: 0.6;
      }
  </style>
{% endblock extra_css %}
{% block content_page %}
{% include 'core/components/nav_bar.html' %}
<div id="tablecontent" class="col-10 mx-auto">
    <h1>{% trans "Transaction Table" %}</h1>
    <table class="table table-light ">
        <caption>Lista de usuarios</caption>
        <thead>
        <tr class=" text-center">
            <th scope="col">id</th>
            <th scope="col">Buyer</th>
            <th scope="col">Amount</th>
            <th scope="col">Total Price</th>
            <th scope="col">Transaction Status</th>
            <th scope="col">Details</th>
        </tr>
        </thead>
        <tbody>
        {% for transaction in page_obj.object_list  %}
        <tr class=" text-center">
            <th scope="row">{{transaction.id}}</th>
            <td>{{transaction.first_name}} {{transaction.last_name}}</td>
            {% for keys,values in cantproduct.items %}
            {% if keys == transaction.id %}
            <td>{{values}}</td>
            {% endif %}
            
            {% endfor %}
            <td>{{transaction.total_amount|floatformat:2}}</td>
            <td class=" {% if transaction.status == 'rejected' %}table-danger {% elif transaction.status == 'approved' %} table-success {% elif transaction.status == 'waiting_for_approval' %} table-warning {% endif %} ">{{transaction.status}}</td>
            <td class="col-3"><p id="informationtransaction" href="" class="checkout-page-btn minicart-btn btn-secondary" onclick="informationtransaction({{transaction.id}})" style="width: auto; opacity: 0.7; cursor: pointer;">{% trans 'Information' %}</p></td>
        </tr>
        <tr class="details{{transaction.id}} d-none" >
            <td colspan="6">
                <table class="table table-light">
                    <tbody id="details{{transaction.id}}"></tbody>
                </table>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>




<!-- muestra el paginador -->
{% if page_obj.has_other_pages %}
<div class="pagination justify-content-center mt-100">
    <nav>
    <ul class="pagination m-0 d-flex align-items-center">
        {% if page_obj.has_previous %}
            <li class="item disabled"><a class="link" href="?page={{ page_obj.previous_page_number }}"> <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"
                viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="icon icon-left">
                <polyline points="15 18 9 12 15 6"></polyline>
            </svg></a></li>


        {% else %}
            <li class="item"><a class="link" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"
                viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="icon icon-left">
                <polyline points="15 18 9 12 15 6"></polyline>
            </svg></a></li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="item"><a class="link" href="#">{{ num }} <span class="sr-only">{% trans '(current)' %}</span></a></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="item"><a class="link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="item"><a class="link" href="?page={{ page_obj.next_page_number }}"><svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"
                viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="icon icon-right">
                <polyline points="9 18 15 12 9 6"></polyline>
            </svg></a></li>
        {% else %}
            <li class="item"><a class="link" href="#"> <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"
                viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="icon icon-right">
                <polyline points="9 18 15 12 9 6"></polyline>
            </svg></a></li>
        {% endif %}
    </ul>
</nav>
</div>
{% endif %}




{% endblock content_page %}

{% block extra_js %}
<!--boton de redireccion-->
<!--boton de redireccion-->
<script>
    var url1="{% url 'almacen:index_admin'%}"
    var url2="{% url 'almacen:ventasadmin'%}"
    var link1 = $('#ventaslink');
    var link2 = $('#homelink');
    link1.attr('href', url2);
    link2.attr('href', url1);

  
  </script>
<!--information transaction-->
<script>
    var URL_information_transaction="{% url 'almacen:detailventas' %}";
    function informationtransaction(idtransaction){
        
        if ($('#details'+idtransaction).text()){
            $('#details'+idtransaction).empty();
            $('.details'+idtransaction).addClass('d-none');

        }
        else{
            $('.details'+idtransaction).removeClass('d-none');
            fetch(URL_information_transaction+"?idtransaction="+idtransaction).then(response=> response.text()).then(
                response=>{
                    $('#details'+idtransaction).empty();
                    
                    $('#details' + idtransaction)
                    .css({
                        opacity: 0.8,
                        height: 0
                    })
                    .hide()
                    .append(response)
                    .slideDown(200)
                    .animate({
                        opacity: 1,
                        height: 'auto'
                    }, 550);

                
                    
                });
        }
        

    }
</script>


{% endblock extra_js %}

almacen/templates/core/checkout.html
{% extends 'core/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
{% trans 'Checkout' %}
{% endblock title%}
{% block extra_css %}
<style>
    #borde{
        border: 1px solid black;
    }
 .submit-button:hover{
    background-color: white;
    color: {{settings.primarycolor_page}};
    border: 1px solid {{settings.primarycolor_page}};
 }
</style>
<style>
    .navtab {
        text-align: center;
      }
      
      .navtab ul {
        list-style: none;
        margin: 0;
        padding: 0;
        display: inline-flex;
        justify-content: center;
      }
      
      .navtab li {
        margin: 0 20px;
      }
      
      .navtab button {
        display: block;
        padding: 10px 20px;
        font-size: 16px;
        color: white;
        text-decoration: none;
        background-color: {{settings.primarycolor_page}};
        border-radius: 15px;
        transition: all 0.3s ease-in-out;
      }
      
      .navtab button:hover {
        background-color: {{settings.primarycolor_page}};
        transform: scale(1.1);
        color: white;
      }
      
      .navtab button.active {
        background-color: #fff;
        color: {{settings.primarycolor_page}};
      }



      select {
        font-size: 16px;
        padding: 8px;
        width: 100%;
        border: none;
        border-radius: 4px;
        box-shadow: 0 0 8px rgba(0, 0, 0, 0.2);
        background-color: #FFFFFF;
        color: #333333;
      }
  
      

      
      
      /* Estilo para el hover del select */
      select:hover {
        background-color: {{settings.primarycolor_page}};
        color: white;
        opacity: 0.65;
        
      }
      
      /* Estilo para el foco del select */
      select:focus {
        outline: none;
        box-shadow: 0 0 8px rgba(0, 0, 0, 0.2), 0 0 0 2px #7FB2F0;
      }
      
      /* Estilo para las opciones */
      option {
        font-size: 16px;
        padding: 8px;
        background-color: #FFFFFF;
        color: #333333;
      }
      
      
      
      /* Estilo para la flecha del select */
      select::-ms-expand {
        display: none;
      }
      
      select::-webkit-select-arrow {
        display: none;
      }
      

</style> 
<style>
    .loader {
        border-radius: 50%;
        width: 50px;
        height: 50px;
        position: relative;
        margin: 0 auto;
      }
      
      .loader::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        border-radius: 50%;
        border: 3px solid {{settings.primarycolor_page}}; /* Cambiar el color aquí */
        border-top-color: transparent;
        animation: loader 1s ease-in-out infinite;
      }
      
      @keyframes loader {
        to {
          transform: rotate(360deg);
        }
      }
      
      
</style>
{% endblock extra_css %}
{% block content_page %}

<main id="MainContent" onload="myFunction()" class="content-for-layout">
    
{% include 'core/components/nav_bar.html' %}
    <div class="checkout-page mt-100">
        <div class="container">
            <div class="checkout-page-wrapper">
                <div class="row">
                    <div id="successfull" class="col-xl-9 col-lg-8 col-md-12 col-12">
                        <div class="section-header mb-3">
                            <h2 class="section-heading">{% trans 'Check out' %}</h2>
                        </div>
    
                        <div class="checkout-progress overflow-hidden">
                            <ol class="checkout-bar px-0">
                                <li class="progress-step step-done"><a>{% trans 'Selection' %}</a></li>
                                <li class="progress-step step-active"><a>{% trans 'Your Details' %}</a></li>
                                <li class="progress-step step-todo"><a>{% trans 'successful' %}</a></li>
                            </ol>
                        </div>
                        


                       

                        <div class="shipping-address-area">
                            <h2 class="shipping-address-heading pb-1">{% trans 'Purchase Information' %}</h2>
                            <div class="shipping-address-form-wrapper">
                                <form id="transaction-form" action="{% url 'almacen:transaction' %}" class="shipping-address-form common-form" method="POST" enctype="multipart/form-data" onsubmit="successful()">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-lg-6 col-md-12 col-12">
                                            <fieldset>
                                                <label class="label">{% trans 'First name' %}</label>
                                                <input type="text" name="first_name" required  />
                                            </fieldset>
                                        </div>
                                        <div class="col-lg-6 col-md-12 col-12">
                                            <fieldset>
                                                <label class="label">{% trans 'Last name' %}</label>
                                                <input type="text" name="last_name" required />
                                            </fieldset>
                                        </div>
                                        <div class="col-lg-6 col-md-12 col-12">
                                            <fieldset>
                                                <label class="label">{% trans 'Email address' %}</label>
                                                <input type="email" name="email" required />
                                            </fieldset>
                                        </div>
                                        <div class="col-lg-6 col-md-12 col-12">
                                            <fieldset>
                                                <label class="label">{% trans 'Phone number' %}</label>
                                                <input type="text" name="phone_number" required />
                                            </fieldset>
                                        </div>
                                        <div class="col-12">
                                            <fieldset>
                                                <label class="label">{% trans 'Address' %}</label>
                                                <input type="text" name="address" required />
                                            </fieldset>
                                        </div>
                                        <div class="col-12">
                                            <fieldset>
                                                <label class="label">{% trans 'payment type' %}</label>
                                                <select name="type_pay" class="form-control">
                                                    <option value="Cash">{% trans 'Cash' %}</option>
                                                    <option  value="Card">{% trans 'Credit or debit card' %}</option>
                                                </select>
                                            </fieldset>
                                        </div> 
                                            
                                    
                                            <button id="" type="submit" class="submit-button checkout-page-btn minicart-btn btn-primary" style="margin:6px;">{% trans 'Enviar' %}</button>
                                        
                                            <a href="{% url 'almacen:dashboard' %}" class="checkout-page-btn minicart-btn btn-secondary" style="margin:6px;">{% trans 'BACK TO SELECTION' %}</a>
                                            
                                            <input type="number" id="totitransaction" value="{{price}}" name="total_amount" hidden>
                                    
                                </div>
                                </form>

                            </div>
                        </div>

                        
                       
                    </div>
                    <div class="col-xl-3 col-lg-4 col-md-12 col-12">
                        <div id="descriptionshopping" class="cart-total-area checkout-summary-area">
                            <h3 class="d-none d-lg-block mb-0 text-center heading_24 mb-4">{% trans 'Order summary' %}</h4>
                                {% for product_id, product_data in cart.items  %}
                            <div class="minicart-item d-flex">
                                <div class="mini-img-wrapper">
                                    <img class="mini-img" src="{{product_data.image}}" alt="img">
                                </div>
                                <div class="product-info">
                                    <h2 class="product-title"><a href="#">{{product_data.name}}</a></h2>
                                    <p class="product-vendor">${{product_data.price|floatformat:2}} x {{product_data.quantity}}</p>
                                </div>
                            </div>
                            {% endfor %}
                            <div class="cart-total-box mt-4 bg-transparent p-0">
                                
                               
                                
                                <hr />
                                <div class="subtotal-item discount-box">
                                    <h4 class="subtotal-title">{% trans 'Total:' %}</h4>
                                    
                                    <p id="totalprice" class="subtotal-value">${{price|floatformat:2}}</p>
                                    
                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>            
    <div id="shipusa" hidden>{{ settings.shippingcost_usa}}</div>
    <div id="shiplatam" hidden>{{ settings.shippingcost_latam}}</div>
    <div id="countrysubtotal" hidden>{{ price}}</div>




</main>

{% endblock content_page %}
{% block extra_js %}


{% comment %} pintar {% endcomment %}
<script>
    var URl_checkout = "{% url 'almacen:checkout'%}"
    function myFunction() {
 fetch(URl_checkout).then(response => response.text()).then(
        response => {
            $('#MainContent').empty()
            $('#MainContent').append(response)
            

        })
      }
    

   
</script>
{% comment %} Copiar hash {% endcomment %}
<script>


      function copy_clipboard(event, button, id) {
        event.preventDefault();
        var target = $(button).siblings(`#kt_referral_link_input_hash${id}`);
        target.select();
        document.execCommand('copy');
        $(button).empty().append('Copiado');
        setTimeout(() => {
          $(button).empty().append('Copiar Hash');
        }, 10000);
      }
      
</script>


<script>
    $('.header-action-item').empty()
    $('.icon-search').empty()
</script>
{% endblock extra_js %}